# Generated by Django 3.1.1 on 2020-10-15 05:15

from django.db import migrations, models
import django.db.models.deletion
import mozilla_django_oidc.auth


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=12, verbose_name='phone')),
            ],
            bases=(mozilla_django_oidc.auth.OIDCAuthenticationBackend, models.Model),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
    ]
