# Generated by Django 3.1.1 on 2021-03-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='code2',
        ),
    ]
