# Generated by Django 3.1.1 on 2020-10-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201028_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
