# Generated by Django 3.1.1 on 2021-03-04 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210302_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='+254728826517', max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+254234567892'. Up to 12 digits allowed with no", regex='^\\+254\\d{9}$')]),
            preserve_default=False,
        ),
    ]
