# Generated by Django 3.1.1 on 2021-03-04 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210304_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+254234567892'. Up to 12 digits allowed with no", regex='^\\+254\\d{9}$')]),
        ),
    ]
